// <auto-generated />
using System;
using Inkwell.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inkwell.Persistence.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(InkwellDbContext))]
    [Migration("20260718163606_AddUserManagement")]
    partial class AddUserManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("RunMessageIndex")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("AgentChatMessages");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastActivityTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastCommittedRunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AgentVersionId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SessionKey")
                        .IsUnique();

                    b.HasIndex("AgentId", "AgentVersionId");

                    b.HasIndex("AgentId", "OwnerUserId", "LastActivityTime");

                    b.ToTable("AgentConversations");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("BuildOptions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<int>("LatestPublishedVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SharedRevokedByAdminTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPublishedVersionId");

                    b.HasIndex("IsShared");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSessionStateEntity", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastRunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("SerializedState")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ConversationId");

                    b.ToTable("AgentSessionStates");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetFileUris")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceFileUris")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("ScriptFileUris")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("AgentSkills");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentToolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParametersJsonSchema")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AgentTools");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PublishedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("AgentVersions");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedUnlockAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("IsLocked");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentChatMessageEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId", "AgentVersionId")
                        .HasPrincipalKey("AgentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSessionStateEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", "Conversation")
                        .WithOne("SessionState")
                        .HasForeignKey("Inkwell.Persistence.EFCore.Entities.AgentSessionStateEntity", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSkillEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentVersionEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("SessionState");
                });
#pragma warning restore 612, 618
        }
    }
}
