// <auto-generated />
using System;
using Inkwell.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inkwell.Persistence.EFCore.Postgres.Migrations
{
    [DbContext(typeof(InkwellDbContext))]
    [Migration("20260718150800_RemoveSkillRowVersion")]
    partial class RemoveSkillRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("run_id");

                    b.Property<int?>("RunMessageIndex")
                        .HasColumnType("integer")
                        .HasColumnName("run_message_index");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id")
                        .HasName("pk_agent_chat_messages");

                    b.HasIndex("ConversationId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_chat_messages_conversation_id_sequence_number");

                    b.ToTable("agent_chat_messages", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_version_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateTimeOffset>("LastActivityTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_time");

                    b.Property<string>("LastCommittedRunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_committed_run_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_key");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id")
                        .HasName("pk_agent_conversations");

                    b.HasIndex("AgentVersionId")
                        .HasDatabaseName("ix_agent_conversations_agent_version_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_agent_conversations_owner_user_id");

                    b.HasIndex("SessionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_conversations_session_key");

                    b.HasIndex("AgentId", "AgentVersionId")
                        .HasDatabaseName("ix_agent_conversations_agent_id_agent_version_id");

                    b.HasIndex("AgentId", "OwnerUserId", "LastActivityTime")
                        .HasDatabaseName("ix_agent_conversations_agent_id_owner_user_id_last_activity_ti");

                    b.ToTable("agent_conversations", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_uri");

                    b.Property<string>("BuildOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("build_options");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_published_version_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<int>("LatestPublishedVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_published_version_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("SharedRevokedByAdminTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shared_revoked_by_admin_time");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("CurrentPublishedVersionId")
                        .HasDatabaseName("ix_agents_current_published_version_id");

                    b.HasIndex("IsShared")
                        .HasDatabaseName("ix_agents_is_shared");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_agents_owner_user_id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSessionStateEntity", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("LastRunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_run_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SerializedState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("serialized_state");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("ConversationId")
                        .HasName("pk_agent_session_states");

                    b.ToTable("agent_session_states", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetFileUris")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("asset_file_uris");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ReferenceFileUris")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reference_file_uris");

                    b.Property<string>("ScriptFileUris")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("script_file_uris");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id")
                        .HasName("pk_agent_skills");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_agent_skills_owner_user_id");

                    b.ToTable("agent_skills", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentToolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJsonSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json_schema");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.HasKey("Id")
                        .HasName("pk_agent_tools");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_tools_name");

                    b.ToTable("agent_tools", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_summary");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateTimeOffset?>("PublishedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_time");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_agent_versions");

                    b.HasAlternateKey("AgentId", "Id")
                        .HasName("ak_agent_versions_agent_id_id");

                    b.HasIndex("AgentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_versions_agent_id_version_number");

                    b.ToTable("agent_versions", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<int>("FailedUnlockAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_unlock_attempts");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super");

                    b.Property<DateTimeOffset?>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IsLocked")
                        .HasDatabaseName("ix_users_is_locked");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentChatMessageEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_chat_messages_agent_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId", "AgentVersionId")
                        .HasPrincipalKey("AgentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_conversations_agent_versions_agent_id_agent_version_id");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSessionStateEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", "Conversation")
                        .WithOne("SessionState")
                        .HasForeignKey("Inkwell.Persistence.EFCore.Entities.AgentSessionStateEntity", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_session_states_agent_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentSkillEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_skills_users_owner_user_id");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentVersionEntity", b =>
                {
                    b.HasOne("Inkwell.Persistence.EFCore.Entities.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_versions_agents_agent_id");
                });

            modelBuilder.Entity("Inkwell.Persistence.EFCore.Entities.AgentConversationEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("SessionState");
                });
#pragma warning restore 612, 618
        }
    }
}
